### ISSUE TITLE
i adding language support but there is a problem

### ISSUE THREAD

**Issue by Mid0aria** [YimMenu/Translations#122]
I am doing turkish language support, but it writes letters such as ş,ı,ğ,ü,ö,ç as ? Is there a unicode support for these?

**Comment by Mid0aria** [comment]
![image](https://github.com/YimMenu/Translations/assets/45801669/b5651db9-3efb-4b46-854b-66e40719e5c6)

**Comment by Yimura** [comment]
We can add the font required to render this font in YimMenu if you'd like.

**Comment by Mid0aria** [comment]
Yeah, that'd be great.

**Comment by gir489returns** [comment]
https://github.com/ocornut/imgui/issues/1880

I'm so tired of orcnut whining about cheaters using ImGui. It's like, he built a hammer, and he's mad some people are using it to hammer nails into boards that they then use to smack people with. What a fat cunt.

**Comment by Mid0aria** [comment]
I will try as soon as the dll is ready

**Comment by Mid0aria** [comment]
![image](https://github.com/YimMenu/Translations/assets/45801669/7ba458bb-60f8-4d2f-aba3-7db480c79f57)

still the same

**Comment by gir489returns** [comment]
You have to select the Turkish language from the menu, which requires changing the language index JSON and a bunch of other stuff.

[index.json](https://github.com/YimMenu/Translations/files/14574745/index.json)

Put this in %AppData%\Roaming\YimMenu\translations and replace the file. Your WIP translation file you've been working on should be named tr_TR.json for the program to hoover it up.

**Comment by Mid0aria** [comment]
![image](https://github.com/YimMenu/Translations/assets/45801669/89aa33a8-dbb6-4fe8-9aae-236ec13b3178)
I did what you said a long time ago.

**Comment by gir489returns** [comment]
You have it marked as Latin not Turkish, you didn't follow my instructions.

**Comment by Mid0aria** [comment]
opps my bad sorry

**Comment by Mid0aria** [comment]
![image](https://github.com/YimMenu/Translations/assets/45801669/2ff09fa0-da2f-4bec-bf81-00b86bedcc3a)

also shows turkish as a blank in the language selection
![image](https://github.com/YimMenu/Translations/assets/45801669/e88e9687-fc48-4eee-9b25-f1e2ccbe5c60)

**Comment by gir489returns** [comment]
Set alphabet_type to turkish.

**Comment by Mid0aria** [comment]
I tried that but it automatically makes latin back

**Comment by gir489returns** [comment]
> I tried that but it automatically makes latin back

Yeah it's because it just grabs the latest from the github repo and replaces index.json then loads the local file. That's annoying. 

[YimMenu.zip](https://github.com/YimMenu/Translations/files/14576365/YimMenu.zip)

Here's a build I made locally that just forces the Latin scenario to load the Turkish characters. If it works, make your PR on the translation repo.

**Comment by gir489returns** [comment]
Can you give me your turkish translation sheet so I can debug it?

**Comment by Mid0aria** [comment]
this is a half translation but it contains all the Turkish characters we need
[tr_TR.json](https://github.com/YimMenu/Translations/files/14576470/tr_TR.json)

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/Translations/assets/100792176/ff1ed600-94bf-4742-bea4-21617ae89dd7)

@Mid0aria It works, it was just a stupid local error, Submit your translation sheet when complete and then it should work. If you need to test, use my build:

[YimMenu.zip](https://github.com/YimMenu/Translations/files/14576605/YimMenu.zip)

**Comment by gir489returns** [comment]
Also, not an expert in Turkish, but shouldn't it say "Çıkar" instead of whatever you have there?

**Comment by Mid0aria** [comment]
Do you mean for proofs

**Comment by gir489returns** [comment]
No for ejecting YimMenu.

**Comment by Mid0aria** [comment]
turks call mod menus script, so I wrote turn off the script

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/Translations/assets/100792176/f4a6c42b-7eaf-4ad4-9d43-8e23b3e7a343)

This makes more sense to me. The function is to remove YimMenu

> turks call mod menus script, so I wrote turn off the script

That doesn't make any sense though, since we're not just turning it off, we're ejecting it entirely from the game.

**Comment by Mid0aria** [comment]
If we say "çıkarma", it's a transposed word.

**Comment by Mid0aria** [comment]
in Turkish electronic terms, switching something off is equivalent to completely disconnecting it.

**Comment by gir489returns** [comment]
Right, I ran into the same issue when doing the Russian version. I guess just do the best you can with what you have.

**Comment by Mid0aria** [comment]
you can be sure I'll do my best.

**Comment by ShinyWasabi** [comment]
I know this is not complete yet, but I've just took a quick look and there are a considerable amount of grammatic/punctuation errors, and translations that are far from their meaning. Like wtf is "Hoşgeldin Abisinin Gülü"? Please stick to the original sentence. You remind me those GTA VC translators from early 2000s lol.

Also, you can consider leaving some words as-is, as they are special to GTA.

**Comment by Mid0aria** [comment]
> I know this is not complete yet, but I've just took a quick look and there are a considerable amount of grammatic/punctuation errors, and translations that are far from their meaning. Like wtf is "Hoşgeldin Abisinin Gülü"? Please stick to the original sentence. You remind me those GTA VC translators from early 2000s lol.
> 
> Also, you can consider leaving some words as-is, as they are special to GTA.

it was a test translation and will be edited according to all spelling rules

**Comment by Yimura** [comment]
@DayibBaba has since added Turkish translations to YimMenu.

**Comment by DayibBaba** [comment]
> I know this is not complete yet, but I've just took a quick look and there are a considerable amount of grammatic/punctuation errors, and translations that are far from their meaning. Like wtf is "Hoşgeldin Abisinin Gülü"? Please stick to the original sentence. You remind me those GTA VC translators from early 2000s lol.
> 
> Also, you can consider leaving some words as-is, as they are special to GTA.

Actually chuckled lol. @Mid0aria abla why u do dis.
