### ISSUE TITLE
After selecting Chinese for translation, injection crashes

### ISSUE THREAD

**Issue by shibaming** [YimMenu/Translations#38]
![O7FJKT_%U%W5`BU7MKN59)X](https://github.com/YimMenu/Translations/assets/118546790/309d44b0-aba6-47ac-9fd3-7385949dbfdd)
I have tried many times and found that it is because of the word '已'. I don't know why, there are no problems with other words

**Comment by sch-lda** [comment]
Try adding "-D CMAKE_CXX_FLAGS='/utf-8'" in the cmake command arguments.
尝试在cmake命令参数中添加-D CMAKE_CXX_FLAGS="/utf-8"
![image-1](https://github.com/YimMenu/Translations/assets/54973190/7df6a176-d258-460c-bd2b-88a08f93e6a4)

**Comment by shibaming** [comment]
Thank you very much for your explanation
