### ISSUE TITLE
I can't do anything in YimMenu/YimMenu

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/Translations#79]
I have this for the past ~2-3 days and i can't do anything. Just view things.
![image](https://github.com/YimMenu/Translations/assets/76223390/f2d34414-681a-4e25-8952-07159a105440)

**Comment by Yimura** [comment]
The menu is outdated and I’m temporarily limiting accessibility to the repo for everyone except prior contributors.

**Comment by pierrelasse** [comment]
Oh okay. You should maybe say this somewhere so people dont get confused.
